### ISSUE TITLE
Typo: 1.17-Exercise-InvestigateLogging/build.gradle

### ISSUE THREAD

**Issue by danielmai** [udacity/ud867#20]
[Line 14][1] by ≠ be

```
3. Modify the `println()` call in our task action to instead by a logging
 statement at the LIFECYCLE level.
```

Suggested change:

```
3. Modify the `println()` call in our task action to instead be a logging
   statement at the LIFECYCLE level.
```
[1]: https://github.com/udacity/ud867/blob/master/1.17-Exercise-InvestigateLogging/build.gradle#L14

**Comment by JeremySilverTongue** [comment]
Fixed. Thanks! Also, I'm super lazy, so this is way more likely to be fixed in a timely fashion if it's a pull request :P
