### ISSUE TITLE
Confused about 1.07-Exercise-ConfigureATask

### ISSUE THREAD

**Issue by kyleparker** [udacity/ud867#28]
So, this may be a dumb question, but I'm confused about the 1.07 exercise for configuring a task. In the quiz on the Udacity web site, the answer for the "group" question was "udacity". Unless I'm missing something, according to the build.gradle, the group should be "Other tasks", correct?

Here are the instructions:

1. Create an empty task definition and name your task "hello".
2. Give your task a description.
3. Add an action to your task which prints "Hello World!"

This does not mention specifying the "group" name for the task. While the solutions.gradle does, it appears to be referencing a different build.gradle (group = 'udacity' // 2. Add task to "udacity" group -- in the build.gradle, #2 is actually "give it a description").

If the build.gradle is followed, shouldn't the resulting "group" be "Other tasks"?

Sorry - just trying to understand everything and confused as to why I got the wrong answer :)

**Comment by JeremySilverTongue** [comment]
Hey Kyle,

Sorry for taking so long to get back to you. You're totally right, that was confusing. The exercise doesn't mention anything about the task group. The quiz is specifically asking you to get the tasks from the `solution.gradle` file. I changed the comments in the solution file so the numbering matches the instructions, and added an additional comment explaining that the group setting is something extra that we didn't ask you to do.

Thanks again!
