### ISSUE TITLE
Exercise 1.17 solution fix for Windows

### ISSUE THREAD

**Issue by zenwaichi** [udacity/ud867#32]
in the solution the line:
`   $ gradle -b solution.gradle --debug hello2 | findstr 'Hello World'`
,should become
`   $ gradle -b solution.gradle --debug hello2 | findstr "Hello World"
`
I love the way you  work @JeremySilverTongue

**Comment by JeremySilverTongue** [comment]
Thanks a ton for the issue and the compliment! Fixed :D
