### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by redbassett** [udacity/ud867#51]
Not gonna fork and pull-request for a simple change:

> Add Interstitial Ad

> Follow these instructions to add an interstitial ad to the free version. Display the add after the user hits the button, but before the joke is shown.

It looks like someone aded a `d` to the second sentence 😉

**Comment by JeremySilverTongue** [comment]
Haha, thanks :D Fixed in https://github.com/udacity/ud867/commit/46bbb5d97e8be9292533f57da70fdacdd5ce648b
